files:
  - source: /*.md
    ignore:
      - README.md
    translation: /%language%/%original_file_name%
  - source: /*.csv
    translation: /%locale%/%original_file_name%
    multilingual_spreadsheet: 1
    first_line_contains_header: 1
    scheme: 'identifier,source_phrase,translation'
